import type { SupabaseClient } from '@supabase/supabase-js';import type { CanonicalActivity,CanonicalCommandIdentity,CanonicalCommandResult,CanonicalOperatorWork } from './contracts.generated';
import { createSecureCommandId } from './secureCommandId';
type Versioned=CanonicalCommandIdentity&{deurId:string;expectedVersion:number};
export class CanonicalDeurCommandRepository{
 constructor(private readonly client:SupabaseClient){}
 start(work:CanonicalOperatorWork,identity:string,draftId:string,optional:{openingMeter?:number;shift?:string;operationalRemarks?:string}={}){const command:CanonicalCommandIdentity&{draft:Record<string,unknown>}={...commandIdentity(work,identity),draft:{id:draftId,...(optional.openingMeter!==undefined?{openingMeter:optional.openingMeter}:{}),...(safeShift(optional.shift)?{shift:safeShift(optional.shift)}:{}),...(optional.operationalRemarks?{operationalRemarks:optional.operationalRemarks}:{})}};return this.execute('command_start_deur_shift',command);}
 transition(work:CanonicalOperatorWork,deurId:string,expectedVersion:number,activity:CanonicalActivity,identity:string,reason?:{id:string;label:string;remarks?:string}){return this.execute('command_transition_deur_activity',{...commandIdentity(work,identity),deurId,expectedVersion,action:actionFor(activity),...(activity==='idle'&&reason?{idleReasonId:reason.id,idleReasonLabelSnapshot:reason.label,...(reason.remarks?{idleReasonRemarks:reason.remarks}:{})}:{})});}
 endShift(work:CanonicalOperatorWork,deurId:string,expectedVersion:number,identity:string=createSecureCommandId(),evidence:{closingMeter?:number;closingLocation?:string}={}){return this.execute('command_complete_deur_shift',{...commandIdentity(work,identity),deurId,expectedVersion,...evidence});}
 submit(work:CanonicalOperatorWork,deurId:string,expectedVersion:number,identity:string){return this.execute('command_submit_deur',{...commandIdentity(work,identity),deurId,expectedVersion}satisfies Versioned);}
 initiateTurnover(work:CanonicalOperatorWork,deurId:string,expectedVersion:number,targetOperatorId:string,identity:string){return this.executeValue('command_initiate_deur_turnover',{...commandIdentity(work,identity),deurId,expectedVersion,targetOperatorId});}
 acceptTurnover(turnoverId:string,operatorId:string,identity:string){return this.executeValue('command_accept_deur_turnover',{commandId:identity,idempotencyKey:identity,turnoverId,operatorId,clientCreatedAt:new Date().toISOString()});}
 private async execute(name:string,command:unknown):Promise<CanonicalCommandResult>{const response=await this.client.schema('erp').rpc(name,{command});if(response.error||!isRecord(response.data))return{success:false,code:'TRANSPORT_FAILURE',retryable:true};const value=response.data;if(value.success!==true)return{success:false,code:typeof value.code==='string'?value.code:'PERSISTENCE_FAILURE',retryable:value.retryable===true,refreshRequired:value.refreshRequired===true};if(!isRecord(value.record)||typeof value.version!=='number'||typeof value.serverOccurredAt!=='string')return{success:false,code:'INVALID_RESPONSE'};const record=value.record;if(typeof record.id!=='string'||typeof record.deur_number!=='string'||typeof record.work_date!=='string'||typeof record.status!=='string'||typeof record.operator_id!=='string')return{success:false,code:'INVALID_RESPONSE'};return{success:true,disposition:value.disposition==='REPLAYED'?'REPLAYED':'ACCEPTED',version:value.version,serverOccurredAt:value.serverOccurredAt,record:{...record,id:record.id,deurNumber:record.deur_number,workDate:record.work_date,status:record.status,operatorId:record.operator_id,rowVersion:value.version}};}
 private async executeValue(name:string,command:unknown):Promise<{success:boolean;code?:string;disposition?:'ACCEPTED'|'REPLAYED'}>{const response=await this.client.schema('erp').rpc(name,{command});if(response.error||!isRecord(response.data))return{success:false,code:'TRANSPORT_FAILURE'};const value=response.data;return value.success===true?{success:true,disposition:value.disposition==='REPLAYED'?'REPLAYED':'ACCEPTED'}:{success:false,code:typeof value.code==='string'?value.code:'PERSISTENCE_FAILURE'};}
}
function commandIdentity(work:CanonicalOperatorWork,identity:string):CanonicalCommandIdentity{return{commandId:identity,idempotencyKey:identity,rentalId:work.rental.id,rentalLineId:work.rentalLine.id,equipmentId:work.equipment.id,operatorId:work.identity.operatorId,assignmentId:work.assignment.id,clientCreatedAt:new Date().toISOString()};}
function actionFor(activity:CanonicalActivity):string{return({operation:'START_OPERATION',idle:'START_IDLE',standby:'START_STANDBY',mealBreak:'START_MEAL_BREAK',breakdown:'START_BREAKDOWN'}as const)[activity];}
function safeShift(value?:string):string|undefined{const normalized=value?.trim();return normalized&&normalized.length<=80&&!/[\u0000-\u001f\u007f]/.test(normalized)?normalized:undefined;}
function isRecord(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
