import type { SupabaseClient } from '@supabase/supabase-js';
import type { CanonicalActivity, CanonicalOpenDeur, CanonicalOperatorWork, CanonicalSessionIdentity } from '../canonical/contracts.generated';
import type { OperatorWorkRepository } from './OperatorWorkRepository';
type Row=Record<string,unknown>;const text=(row:Row,key:string)=>typeof row[key]==='string'?row[key] as string:undefined;const numeric=(row:Row,key:string)=>typeof row[key]==='number'?row[key] as number:undefined;
export class SupabaseOperatorWorkRepository implements OperatorWorkRepository {
  readonly kind='CANONICAL_UAT' as const;constructor(private readonly client:SupabaseClient){}
  async getCurrentWork(identity:CanonicalSessionIdentity):Promise<CanonicalOperatorWork|null>{
    const assignmentResult=await this.client.schema('erp').from('assignments').select('id,equipment_id,project_id,status').eq('operator_id',identity.operatorId).eq('status','Active').limit(1).maybeSingle();const assignment=assignmentResult.data as Row|null;
    if(assignmentResult.error)throw new Error('Canonical Assignment projection failed.');if(!assignment)return null;const assignmentId=text(assignment,'id'),equipmentId=text(assignment,'equipment_id'),projectId=text(assignment,'project_id');if(!assignmentId||!equipmentId||!projectId)throw new Error('Canonical Assignment projection is incomplete.');
    const lineResult=await this.client.schema('erp').from('rental_equipment_lines').select('id,rental_id,status,operational_metadata').eq('assignment_id',assignmentId).eq('operator_id',identity.operatorId).in('status',['Released','Active']).limit(1).maybeSingle();const line=lineResult.data as Row|null;
    if(lineResult.error)throw new Error('Canonical Rental Line projection failed.');if(!line)return null;const lineId=text(line,'id'),rentalId=text(line,'rental_id');if(!lineId||!rentalId)throw new Error('Canonical Rental Line projection is incomplete.');
    const [equipmentResult,rentalResult,deurResult]=await Promise.all([this.client.schema('erp').from('equipment').select('id,equipment_name,asset_no,current_reading').eq('id',equipmentId).maybeSingle(),this.client.schema('erp').from('rentals').select('id,rental_number,status').eq('id',rentalId).maybeSingle(),this.client.schema('erp').from('deurs').select('id,deur_number,work_date,status,row_version,operator_id,shift').eq('rental_equipment_line_id',lineId).is('previous_revision_id',null).in('status',['Draft','In Progress']).order('created_at',{ascending:false}).limit(1).maybeSingle()]);
    if(equipmentResult.error||rentalResult.error||deurResult.error)throw new Error('Canonical Operator work projection failed.');const equipment=equipmentResult.data as Row|null,rental=rentalResult.data as Row|null,deur=deurResult.data as Row|null;if(!equipment||!rental)throw new Error('Canonical Operator work projection is incomplete.');const equipmentName=text(equipment,'equipment_name'),assetNumber=text(equipment,'asset_no'),rentalNumber=text(rental,'rental_number');if(!equipmentName||!assetNumber||!rentalNumber)throw new Error('Canonical Operator work projection is incomplete.');let openDeur=deur?this.mapOpenDeur(deur):undefined;
    if(openDeur){const eventResult=await this.client.schema('erp').from('deur_events').select('activity_type').eq('deur_id',openDeur.id).eq('is_open',true).neq('activity_type','shift').limit(1).maybeSingle();if(eventResult.error)throw new Error('Canonical active activity projection failed.');const activity=text((eventResult.data as Row|null)??{},'activity_type');if(isCanonicalActivity(activity))openDeur={...openDeur,activeActivity:activity};}
    const operationalMetadata=isRecord(line.operational_metadata)?line.operational_metadata:{};const expectation=isRecord(operationalMetadata.deurExpectationSnapshot)?operationalMetadata.deurExpectationSnapshot:{};
    return {identity,assignment:{id:assignmentId,projectId,status:text(assignment,'status')??'Active'},equipment:{id:equipmentId,name:equipmentName,assetNumber,...(numeric(equipment,'current_reading')!==undefined?{currentReading:numeric(equipment,'current_reading')}: {})},rental:{id:rentalId,rentalNumber,status:text(rental,'status')??'',...(typeof expectation.billingMethod==='string'?{billingMethod:expectation.billingMethod}: {})},rentalLine:{id:lineId,status:text(line,'status')??'',operationalMetadata},...(openDeur?{openDeur}: {})};
  }
  private mapOpenDeur(row:Row):CanonicalOpenDeur{const id=text(row,'id'),deurNumber=text(row,'deur_number'),workDate=text(row,'work_date'),status=text(row,'status'),operatorId=text(row,'operator_id'),rowVersion=numeric(row,'row_version');if(!id||!deurNumber||!workDate||!status||!operatorId||rowVersion===undefined)throw new Error('Canonical open DEUR projection is incomplete.');return{id,deurNumber,workDate,status,operatorId,rowVersion,...(text(row,'shift')?{shift:text(row,'shift')}: {})};}
}
function isRecord(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function isCanonicalActivity(value:unknown):value is CanonicalActivity{return value==='operation'||value==='idle'||value==='standby'||value==='mealBreak'||value==='breakdown';}
