import type { SupabaseClient } from '@supabase/supabase-js';
import type { CanonicalActivity, CanonicalOpenDeur, CanonicalOperatorWork, CanonicalSessionIdentity, CanonicalTurnoverOperator } from '../canonical/contracts.generated';
import type { OperatorWorkRepository } from './OperatorWorkRepository';
type Row=Record<string,unknown>;const text=(row:Row,key:string)=>typeof row[key]==='string'?row[key] as string:undefined;const numeric=(row:Row,key:string)=>typeof row[key]==='number'?row[key] as number:undefined;
export class SupabaseOperatorWorkRepository implements OperatorWorkRepository {
  readonly kind='CANONICAL_UAT' as const;constructor(private readonly client:SupabaseClient){}
  async getCurrentWorks(identity:CanonicalSessionIdentity):Promise<CanonicalOperatorWork[]>{
    const assignments=await this.client.schema('erp').from('assignments').select('id,equipment_id,project_id,status').eq('operator_id',identity.operatorId).eq('status','Active').order('id');
    if(assignments.error)throw new Error('Canonical Assignment projection failed.');
    const ids=(assignments.data??[]).map((a:any)=>String(a.id)); if(!ids.length)return this.getTurnoverWorks(identity);
    const lines=await this.client.schema('erp').from('rental_equipment_lines').select('id,rental_id,status,assignment_id,equipment_id,operator_id,operational_metadata').in('assignment_id',ids).eq('operator_id',identity.operatorId).in('status',['Released','Active']).order('id');
    if(lines.error)throw new Error('Canonical Rental Line projection failed.');
    const seen=new Set<string>(); const works:CanonicalOperatorWork[]=[];
    for(const line of (lines.data??[]) as any[]){const lineId=String(line.id);if(seen.has(lineId))throw new Error('Canonical Rental Line projection is ambiguous.');seen.add(lineId);const assignment=(assignments.data??[]).find((a:any)=>String(a.id)===String(line.assignment_id));if(!assignment)continue;const [eq,rental]=await Promise.all([this.client.schema('erp').from('equipment').select('id,equipment_name,asset_no,current_reading').eq('id',line.equipment_id).maybeSingle(),this.client.schema('erp').from('rentals').select('id,rental_number,status').eq('id',line.rental_id).maybeSingle()]);if(eq.error||rental.error||!eq.data||!rental.data)continue;const deurs=await this.client.schema('erp').from('deurs').select('id,deur_number,work_date,status,row_version,operator_id,shift,created_at').eq('rental_equipment_line_id',lineId).is('previous_revision_id',null).order('created_at',{ascending:false}).limit(32);if(deurs.error)continue;const metadata=isRecord(line.operational_metadata)?line.operational_metadata:{};const expectation=isRecord(metadata.deurExpectationSnapshot)?metadata.deurExpectationSnapshot:{};const timezone=readExpectationTimezone(expectation);const selected=selectCanonicalDeurs((deurs.data??[]) as Row[],timezone);works.push({identity,assignment:{id:String(assignment.id),projectId:String(assignment.project_id),status:String(assignment.status)},equipment:{id:String(eq.data.id),name:String(eq.data.equipment_name),assetNumber:String(eq.data.asset_no),...(typeof eq.data.current_reading==='number'?{currentReading:eq.data.current_reading}:{})},rental:{id:String(rental.data.id),rentalNumber:String(rental.data.rental_number),status:String(rental.data.status),...(typeof expectation.billingMethod==='string'?{billingMethod:expectation.billingMethod}:{})},rentalLine:{id:lineId,status:String(line.status),operationalMetadata:metadata},...(selected.daily?{dailyDeur:this.mapOpenDeur(selected.daily)}:{}),...(selected.open?{openDeur:this.mapOpenDeur(selected.open)}:{})});}
    for(const work of works){if(!work.openDeur)continue;const eventResult=await this.client.schema('erp').from('deur_events').select('activity_type').eq('deur_id',work.openDeur.id).eq('is_open',true).neq('activity_type','shift');if(eventResult.error)throw new Error('Canonical active activity projection failed.');if((eventResult.data??[]).length>1)throw new Error('Canonical active activity projection is ambiguous.');const activity=text(((eventResult.data??[])[0] as Row|null)??{},'activity_type');if(isCanonicalActivity(activity)){work.openDeur={...work.openDeur,activeActivity:activity};if(work.dailyDeur?.id===work.openDeur.id)work.dailyDeur={...work.dailyDeur,activeActivity:activity};}}
    for(const turnoverWork of await this.getTurnoverWorks(identity)){const existingIndex=works.findIndex(work=>work.rentalLine.id===turnoverWork.rentalLine.id);if(existingIndex>=0){const existing=works[existingIndex];works[existingIndex]={...existing,custody:turnoverWork.custody,openDeur:turnoverWork.openDeur,dailyDeur:turnoverWork.dailyDeur};}else{seen.add(turnoverWork.rentalLine.id);works.push(turnoverWork);}}
    return works.sort((a,b)=>a.rental.rentalNumber.localeCompare(b.rental.rentalNumber)||a.equipment.assetNumber.localeCompare(b.equipment.assetNumber));
  }
  async getCurrentWork(identity:CanonicalSessionIdentity):Promise<CanonicalOperatorWork|null>{
    const assignmentResult=await this.client.schema('erp').from('assignments').select('id,equipment_id,project_id,status').eq('operator_id',identity.operatorId).eq('status','Active').limit(1).maybeSingle();const assignment=assignmentResult.data as Row|null;
    if(assignmentResult.error)throw new Error('Canonical Assignment projection failed.');if(!assignment)return null;const assignmentId=text(assignment,'id'),equipmentId=text(assignment,'equipment_id'),projectId=text(assignment,'project_id');if(!assignmentId||!equipmentId||!projectId)throw new Error('Canonical Assignment projection is incomplete.');
    const lineResult=await this.client.schema('erp').from('rental_equipment_lines').select('id,rental_id,status,operational_metadata').eq('assignment_id',assignmentId).eq('operator_id',identity.operatorId).in('status',['Released','Active']).limit(1).maybeSingle();const line=lineResult.data as Row|null;
    if(lineResult.error)throw new Error('Canonical Rental Line projection failed.');if(!line)return null;const lineId=text(line,'id'),rentalId=text(line,'rental_id');if(!lineId||!rentalId)throw new Error('Canonical Rental Line projection is incomplete.');
    const [equipmentResult,rentalResult,deurResult]=await Promise.all([this.client.schema('erp').from('equipment').select('id,equipment_name,asset_no,current_reading').eq('id',equipmentId).maybeSingle(),this.client.schema('erp').from('rentals').select('id,rental_number,status').eq('id',rentalId).maybeSingle(),this.client.schema('erp').from('deurs').select('id,deur_number,work_date,status,row_version,operator_id,shift,created_at').eq('rental_equipment_line_id',lineId).is('previous_revision_id',null).order('created_at',{ascending:false}).limit(32)]);
    if(equipmentResult.error||rentalResult.error||deurResult.error)throw new Error('Canonical Operator work projection failed.');const equipment=equipmentResult.data as Row|null,rental=rentalResult.data as Row|null,deurs=(deurResult.data??[]) as Row[];if(!equipment||!rental)throw new Error('Canonical Operator work projection is incomplete.');const equipmentName=text(equipment,'equipment_name'),assetNumber=text(equipment,'asset_no'),rentalNumber=text(rental,'rental_number');if(!equipmentName||!assetNumber||!rentalNumber)throw new Error('Canonical Operator work projection is incomplete.');const operationalMetadata=isRecord(line.operational_metadata)?line.operational_metadata:{};const expectation=isRecord(operationalMetadata.deurExpectationSnapshot)?operationalMetadata.deurExpectationSnapshot:{};const timezone=readExpectationTimezone(expectation);const selected=selectCanonicalDeurs(deurs,timezone);let openDeur=selected.open?this.mapOpenDeur(selected.open):undefined;const dailyDeur=selected.daily?this.mapOpenDeur(selected.daily):undefined;
    if(openDeur){const eventResult=await this.client.schema('erp').from('deur_events').select('activity_type').eq('deur_id',openDeur.id).eq('is_open',true).neq('activity_type','shift').limit(1).maybeSingle();if(eventResult.error)throw new Error('Canonical active activity projection failed.');const activity=text((eventResult.data as Row|null)??{},'activity_type');if(isCanonicalActivity(activity))openDeur={...openDeur,activeActivity:activity};}
    const work={identity,assignment:{id:assignmentId,projectId,status:text(assignment,'status')??'Active'},equipment:{id:equipmentId,name:equipmentName,assetNumber,...(numeric(equipment,'current_reading')!==undefined?{currentReading:numeric(equipment,'current_reading')}: {})},rental:{id:rentalId,rentalNumber,status:text(rental,'status')??'',...(typeof expectation.billingMethod==='string'?{billingMethod:expectation.billingMethod}: {})},rentalLine:{id:lineId,status:text(line,'status')??'',operationalMetadata},...(openDeur?{openDeur}: {}),...(dailyDeur?{dailyDeur}: {})};
    return work;
  }
  async loadTurnoverTargets(work:CanonicalOperatorWork):Promise<void>{await this.attachTurnoverTargets(work);}
  private async attachTurnoverTargets(work:CanonicalOperatorWork):Promise<void>{
    if(!work.openDeur)return;
    const result=await this.client.schema('erp').rpc('read_eligible_deur_turnover_operators',{command:{deurId:work.openDeur.id,rentalLineId:work.rentalLine.id,operatorId:work.identity.operatorId}});
    if(result.error||!isRecord(result.data)||result.data.success!==true)return;
    const rows=Array.isArray(result.data.operators)?result.data.operators:[];
    work.turnoverTargets=rows.filter(isRecord).map(row=>({operatorId:text(row,'operatorId')??'',displayName:text(row,'displayName')??'',status:text(row,'status')??''})).filter(item=>item.operatorId&&item.displayName&&item.status==='Active');
  }
  private mapOpenDeur(row:Row):CanonicalOpenDeur{const id=text(row,'id'),deurNumber=text(row,'deur_number'),workDate=text(row,'work_date'),status=text(row,'status'),operatorId=text(row,'operator_id'),rowVersion=numeric(row,'row_version');if(!id||!deurNumber||!workDate||!status||!operatorId||rowVersion===undefined)throw new Error('Canonical open DEUR projection is incomplete.');return{id,deurNumber,workDate,status,operatorId,rowVersion,...(text(row,'shift')?{shift:text(row,'shift')}: {})};}
  private async getTurnoverWorks(identity:CanonicalSessionIdentity):Promise<CanonicalOperatorWork[]>{
    console.info('TURNOVER_WORK_READ_START',{operatorId:identity.operatorId,rpc:'read_current_operator_deur_turnover_work'});
    const result=await this.client.schema('erp').rpc('read_current_operator_deur_turnover_work');
    const rows=isRecord(result.data)&&Array.isArray(result.data.work)?result.data.work:[];
    const candidate=isRecord(rows[0])?rows[0]:{};
    const candidateDeur=isRecord(candidate.deur)?candidate.deur:{};
    const candidateLine=isRecord(candidate.line)?candidate.line:{};
    const candidateAssignment=isRecord(candidate.assignment)?candidate.assignment:{};
    const candidateEquipment=isRecord(candidate.equipment)?candidate.equipment:{};
    const candidateRental=isRecord(candidate.rental)?candidate.rental:{};
    const inputChecks={hasDeur:isRecord(candidate.deur),hasLine:isRecord(candidate.line),hasAssignment:isRecord(candidate.assignment),hasEquipment:isRecord(candidate.equipment),hasRental:isRecord(candidate.rental),hasTurnoverId:Boolean(text(candidate,'turnoverId')),hasCustody:Boolean(text(candidate,'primaryOperatorId')&&text(candidate,'currentAuthorizedOperatorId')&&text(candidate,'turnoverToOperatorId')),hasLineId:Boolean(text(candidateLine,'id')),hasAssignmentId:Boolean(text(candidateAssignment,'id')),hasProjectId:Boolean(text(candidateAssignment,'projectId')),hasEquipmentIdentity:Boolean(text(candidateEquipment,'id')&&text(candidateEquipment,'name')&&text(candidateEquipment,'assetNumber')),hasRentalIdentity:Boolean(text(candidateRental,'id')&&text(candidateRental,'rentalNumber')),hasDeurIdentity:Boolean(text(candidateDeur,'id')&&text(candidateDeur,'deurNumber')&&text(candidateDeur,'workDate')&&text(candidateDeur,'status')&&text(candidateDeur,'operatorId')&&numeric(candidateDeur,'version')!==undefined)};
    console.info('TURNOVER_WORK_MAP_INPUT',JSON.stringify(inputChecks));
    console.info('TURNOVER_WORK_READ_RESULT',{success:!result.error&&isRecord(result.data)&&result.data.success===true,count:rows.length,errorCode:result.error?.code??null,operatorId:identity.operatorId,deurNumbers:rows.filter(isRecord).map(row=>isRecord(row.deur)?text(row.deur,'deurNumber'):undefined).filter(Boolean)});
    if(result.error||!isRecord(result.data)||result.data.success!==true)return[];const works:CanonicalOperatorWork[]=[];for(const value of rows){if(!isRecord(value)||!isRecord(value.deur)||!isRecord(value.line)||!isRecord(value.assignment)||!isRecord(value.equipment)||!isRecord(value.rental))continue;const deur=value.deur,line=value.line,assignment=value.assignment,equipment=value.equipment,rental=value.rental;const lineId=text(line,'id'),deurId=text(deur,'id'),turnoverId=text(value,'turnoverId'),turnoverStatus=text(value,'turnoverStatus'),primaryOperatorId=text(value,'primaryOperatorId'),currentAuthorizedOperatorId=text(value,'currentAuthorizedOperatorId'),turnoverToOperatorId=text(value,'turnoverToOperatorId'),equipmentId=text(equipment,'id'),equipmentName=text(equipment,'name'),assetNumber=text(equipment,'assetNumber'),rentalId=text(rental,'id'),rentalNumber=text(rental,'rentalNumber'),assignmentId=text(assignment,'id'),projectId=text(assignment,'projectId'),deurNumber=text(deur,'deurNumber'),workDate=text(deur,'workDate'),status=text(deur,'status'),operatorId=text(deur,'operatorId'),rowVersion=numeric(deur,'version'),activeActivity=text(deur,'activeActivity');if(!lineId||!deurId||!turnoverId||(turnoverStatus!=='PENDING'&&turnoverStatus!=='ACCEPTED')||!primaryOperatorId||!currentAuthorizedOperatorId||!turnoverToOperatorId||!equipmentId||!equipmentName||!assetNumber||!rentalId||!rentalNumber||!assignmentId||!projectId||!deurNumber||!workDate||!status||!operatorId||rowVersion===undefined)continue;const openDeur:CanonicalOpenDeur={id:deurId,deurNumber,workDate,status,operatorId,rowVersion,...(isCanonicalActivity(activeActivity)?{activeActivity}: {})};works.push({identity,assignment:{id:assignmentId,projectId,status:text(assignment,'status')??'Active'},equipment:{id:equipmentId,name:equipmentName,assetNumber,...(numeric(equipment,'currentReading')!==undefined?{currentReading:numeric(equipment,'currentReading')}: {})},rental:{id:rentalId,rentalNumber,status:text(rental,'status')??''},rentalLine:{id:lineId,status:text(line,'status')??'',operationalMetadata:isRecord(line.operationalMetadata)?line.operationalMetadata:{}},custody:{primaryOperatorId,currentAuthorizedOperatorId,turnoverId,turnoverToOperatorId,turnoverStatus},openDeur,dailyDeur:openDeur});}return works;}
}
function isRecord(value:unknown):value is Record<string,unknown>{return Boolean(value)&&typeof value==='object'&&!Array.isArray(value);}
function isCanonicalActivity(value:unknown):value is CanonicalActivity{return value==='operation'||value==='idle'||value==='standby'||value==='mealBreak'||value==='breakdown';}
function readExpectationTimezone(expectation:Record<string,unknown>):string{const policy=isRecord(expectation.policy)?expectation.policy:{};return typeof policy.timezone==='string'&&policy.timezone?policy.timezone:'UTC';}
export function canonicalWorkDate(now:Date,timezone:string):string{const parts=new Intl.DateTimeFormat('en',{timeZone:timezone,year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(now);const value=(type:Intl.DateTimeFormatPartTypes)=>parts.find(part=>part.type===type)?.value;if(!value('year')||!value('month')||!value('day'))throw new Error('Canonical work date projection failed.');return`${value('year')}-${value('month')}-${value('day')}`;}
export function selectCanonicalDeurs(rows:Row[],timezone:string,now=new Date()):{open?:Row;daily?:Row}{const open=rows.find(row=>text(row,'status')==='Draft'||text(row,'status')==='In Progress');if(open)return{open,daily:open};const today=canonicalWorkDate(now,timezone);const daily=rows.find(row=>text(row,'work_date')===today);return daily?{daily}:{ };}
