import { useEffect, useState } from 'react';
import { Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { Button } from './Button';
import { SyncBanner } from './SyncBanner';
import { Card } from './Card';
import { useAuth } from '@/lib/auth';
import { useTheme } from '@/lib/useTheme';
import { mapMobileActivity, type CanonicalMobileActivity } from '@/lib/canonical/activityMapping';
import { isDeurOpenForOperatorMutation, isDeurReadOnly } from '@/lib/canonical/deurLifecycle';
import { spacing } from '@/lib/theme';
import { StatusChip } from './StatusChip';
import { CanonicalDeurDetailsSheet } from './CanonicalDeurDetailsSheet';

const ACTIVITIES: CanonicalMobileActivity[] = ['Operating', 'Idle', 'Standby', 'Meal Break', 'Breakdown'];
const IDLE_REASONS = ['material', 'trucks', 'instructions', 'customer', 'access', 'traffic', 'weather', 'site preparation'];
const custodyDisplayName = (operatorId: string, displayName: string | undefined, identity: { operatorId: string; operatorName: string }) => displayName?.trim() || (operatorId === identity.operatorId ? identity.operatorName : 'Unavailable');

export function CanonicalDeurOperatorPanel() {
  const { canonicalWork: work, canonicalWorks, selectCanonicalWork, canonicalBusy, offlineSyncState, offlinePendingCount, uatSessionState, offlineContinuationSnapshot, startCanonicalDeur, transitionCanonicalActivity, endCanonicalShift, submitCanonicalDeur, scenario8Replay, replayScenario8Terminal, initiateCanonicalTurnover, acceptCanonicalTurnover } = useAuth();
  const { colors: c } = useTheme();
  const insets = useSafeAreaInsets();
  const [message, setMessage] = useState<string | null>(null);
  const [idleReason, setIdleReason] = useState<string | null>(null);
  const [remarks, setRemarks] = useState('');
  const [openingHourMeter, setOpeningHourMeter] = useState('');
  const [openingOdometer, setOpeningOdometer] = useState('');
  const [closingHourMeter, setClosingHourMeter] = useState('');
  const [closingOdometer, setClosingOdometer] = useState('');
  const [showTurnoverTargets, setShowTurnoverTargets] = useState(false);
  const [showDetails, setShowDetails] = useState(false);
  useEffect(() => {
    if (offlineSyncState === 'ONLINE' && offlinePendingCount === 0 && message?.includes('queued locally')) setMessage(null);
  }, [offlineSyncState, offlinePendingCount, message]);
  const act = async (label: string, action: () => Promise<{ success: boolean; code?: string }>) => {
    setMessage(null);
    const result = await action();
    const successMessage = label === 'Start DEUR' ? 'DEUR started successfully.' : label === 'End Shift' ? 'Shift ended successfully.' : label === 'Submit' ? 'DEUR submitted successfully.' : `${label} completed successfully.`;
    setMessage(result.success ? successMessage : result.code === 'LOCAL_PENDING' ? `${label} is queued and awaiting confirmation.` : `${label} could not be completed (${result.code ?? 'UNKNOWN'}).`);
  };
  if (!work && canonicalWorks.length > 1) return <ScrollView style={{ backgroundColor: c.background }} contentContainerStyle={[styles.content, { paddingTop: spacing.lg + insets.top }]}><Text style={[styles.title, { color: c.textPrimary }]}>Select equipment work</Text>{canonicalWorks.map(item => <Button key={item.rentalLine.id} label={`${item.equipment.assetNumber} · ${item.rental.rentalNumber}`} variant="secondary" onPress={() => selectCanonicalWork(item.rentalLine.id)} />)}</ScrollView>;
  if (!work) return <View style={[styles.center, { backgroundColor: c.background }]}><Text style={{ color: c.textMuted }}>No current assignment found. Contact your supervisor for help.</Text></View>;
  const deur = work.openDeur ?? work.dailyDeur;
  const isOpen = Boolean(work.openDeur);
  const isReadOnly = Boolean(deur && isDeurReadOnly(deur.status));
  const offlineContinuation = uatSessionState === 'OFFLINE_CONTINUATION' || uatSessionState === 'OFFLINE_EXPIRED';
  const offlineReadOnly = uatSessionState === 'OFFLINE_EXPIRED' || uatSessionState === 'REAUTH_REQUIRED';
  const remainingMs = offlineContinuationSnapshot ? Math.max(0, new Date(offlineContinuationSnapshot.lastSuccessfulOnlineAuthorizationAt).getTime() + 12 * 60 * 60 * 1000 - Date.now()) : 0;
  const remainingLabel = `${Math.floor(remainingMs / 3_600_000)}h ${Math.floor((remainingMs % 3_600_000) / 60_000)}m`;
  const canAcceptTurnover = work.custody?.turnoverStatus === 'PENDING' && work.custody.turnoverToOperatorId === work.identity.operatorId;
  const hasCustodyAuthority = !work.custody || work.custody.currentAuthorizedOperatorId === work.identity.operatorId;
  const canMutateOperationalState = isOpen && !isReadOnly && hasCustodyAuthority;
  const canMutateActivity = canMutateOperationalState && isDeurOpenForOperatorMutation(deur?.status ?? '');
  const primaryOperatorDisplayName = work.custody ? custodyDisplayName(work.custody.primaryOperatorId, work.custody.primaryOperatorDisplayName, work.identity) : null;
  const currentOperatorDisplayName = work.custody ? custodyDisplayName(work.custody.currentAuthorizedOperatorId, work.custody.currentAuthorizedOperatorDisplayName, work.identity) : null;
  const canStartNew = !isOpen && uatSessionState === 'ONLINE_AUTHENTICATED';
  const meterRequired = work.meterRequirement !== 'none' && work.meterRequirement !== undefined;
  const openingHour = deur?.openingHourMeter;
  const openingOdo = deur?.openingOdometer;
  const parseMeter = (value: string) => value.trim() === '' ? undefined : Number(value);
  const endShift = async () => {
    if (!meterRequired) return endCanonicalShift();
    const hour = parseMeter(closingHourMeter); const odo = parseMeter(closingOdometer);
    const required = work.meterRequirement === 'hourMeter' ? [hour] : work.meterRequirement === 'odometer' ? [odo] : [hour, odo];
    if (required.some(value => value === undefined || !Number.isFinite(value) || value < 0)) {
      setMessage('Enter valid non-negative closing readings before ending the shift.');
      return { success: false, code: 'CLOSING_METER_REQUIRED' };
    }
    if ((hour !== undefined && openingHour !== undefined && hour < openingHour) || (odo !== undefined && openingOdo !== undefined && odo < openingOdo)) {
      setMessage('Closing readings must be at least their opening readings.');
      return { success: false, code: 'CLOSING_METER_BELOW_OPENING' };
    }
    return endCanonicalShift({ ...(hour !== undefined ? { closingHourMeter: hour } : {}), ...(odo !== undefined ? { closingOdometer: odo } : {}) });
  };
  const formatMinutes = (minutes?: number) => minutes === undefined ? '—' : `${minutes} min`;
  const shiftMinutes = deur?.startedAt ? Math.max(0, Math.round(((deur.endedAt ? new Date(deur.endedAt).getTime() : Date.now()) - new Date(deur.startedAt).getTime()) / 60000)) : undefined;
  return <ScrollView style={{ backgroundColor: c.background }} contentContainerStyle={[styles.content, { paddingTop: spacing.lg + insets.top, paddingBottom: spacing.xxxl + insets.bottom }]}>
    <Text style={[styles.title, { color: c.textPrimary }]}>Digital DEUR</Text>
    {offlineSyncState !== 'ONLINE' ? <><SyncBanner status={offlineSyncState === 'OFFLINE' ? 'offline' : offlineSyncState === 'SYNC_CONFLICT' ? 'failed' : 'pending'} />{offlinePendingCount > 0 ? <Text style={{ color: c.textMuted }}>Pending updates: {offlinePendingCount}</Text> : null}</> : null}
    {offlineContinuation && offlineContinuationSnapshot ? <Card style={styles.card}><Text style={[styles.section, { color: c.textPrimary }]}>OFFLINE SESSION</Text><Text style={{ color: c.textSecondary }}>{offlineContinuationSnapshot.operatorDisplayName}</Text><Text style={{ color: c.textSecondary }}>Current DEUR: {offlineContinuationSnapshot.deurNumber}</Text><Text style={{ color: c.textMuted }}>Last verified online: {new Date(offlineContinuationSnapshot.lastSuccessfulOnlineAuthorizationAt).toLocaleString()}</Text><Text style={{ color: offlineReadOnly ? c.red500 : c.amber500 }}>{offlineReadOnly ? 'Offline authorization has expired. Connect to revalidate before making changes.' : `Offline continuation remaining: ${remainingLabel}`}</Text><Text style={{ color: c.textMuted }}>Changes are stored locally and synchronize only after revalidation.</Text></Card> : null}
    <Card style={styles.card}><Text style={[styles.name, { color: c.textPrimary }]}>{work.equipment.name}</Text><Text style={{ color: c.textMuted }}>{work.equipment.assetNumber}</Text><Text style={{ color: c.textSecondary }}>Rental {work.rental.rentalNumber}</Text><Text style={{ color: c.textSecondary }}>Assignment status: {work.assignment.status}</Text>{work.rental.billingMethod ? <Text style={{ color: c.textSecondary }}>Billing method: {work.rental.billingMethod}</Text> : null}</Card>
    {!deur ? <><Text style={{ color: c.textMuted }}>Work date and DEUR number will be assigned automatically.</Text>{meterRequired ? <><Text style={{ color: c.textMuted }}>Opening readings required by policy: {meterRequirementLabel(work.meterRequirement)}.</Text>{work.meterRequirement === 'hourMeter' || work.meterRequirement === 'both' ? <TextInput accessibilityLabel="Opening hour meter" value={openingHourMeter} onChangeText={setOpeningHourMeter} placeholder="Opening hour meter" placeholderTextColor={c.textMuted} keyboardType="numeric" style={[styles.remarks, { color: c.textPrimary, borderColor: c.inputBorder, backgroundColor: c.inputBg }]} /> : null}{work.meterRequirement === 'odometer' || work.meterRequirement === 'both' ? <TextInput accessibilityLabel="Opening odometer" value={openingOdometer} onChangeText={setOpeningOdometer} placeholder="Opening odometer" placeholderTextColor={c.textMuted} keyboardType="numeric" style={[styles.remarks, { color: c.textPrimary, borderColor: c.inputBorder, backgroundColor: c.inputBg }]} /> : null}</> : null}<TextInput value={remarks} onChangeText={setRemarks} placeholder="Optional shift remarks" placeholderTextColor={c.textMuted} style={[styles.remarks, { color: c.textPrimary, borderColor: c.inputBorder, backgroundColor: c.inputBg }]} multiline /><Button label="START NEW DEUR" disabled={canonicalBusy || uatSessionState !== 'ONLINE_AUTHENTICATED'} loading={canonicalBusy} onPress={() => void act('Start DEUR', () => startCanonicalDeur({ ...(openingHourMeter.trim() ? { openingHourMeter: Number(openingHourMeter) } : {}), ...(openingOdometer.trim() ? { openingOdometer: Number(openingOdometer) } : {}), operationalRemarks: remarks.trim() || undefined }))} /></> : <>
      <Card style={styles.card}><View style={styles.deurHeader}><View style={{ flex: 1 }}><Text style={[styles.overline, { color: c.blue600 }]}>DIGITAL DEUR</Text><Text style={[styles.name, { color: c.textPrimary }]}>{deur.deurNumber}</Text><Text style={{ color: c.textSecondary }}>Work date · {deur.workDate}</Text><Text style={{ color: c.textSecondary }}>Status: {deur.status}</Text></View><StatusChip label={deur.status.toUpperCase()} variant={statusVariant(deur.status)} /></View><View style={styles.kpiGrid}><Metric label="Duration" value={formatMinutes(shiftMinutes)} color={c.textPrimary} /><Metric label="Operating" value={formatMinutes(deur.totalOperatingMinutes)} color={c.emerald500} /><Metric label="Idle" value={formatMinutes(deur.totalIdleMinutes)} color={c.amber500} /><Metric label="Standby" value={formatMinutes(deur.totalStandbyMinutes)} color={c.blue600} /></View><View style={styles.kpiGrid}><Metric label="Meal break" value={formatMinutes(deur.totalMealBreakMinutes)} color={c.textSecondary} /><Metric label="Breakdown" value={formatMinutes(deur.totalMaintenanceMinutes)} color={c.red500} /></View>{deur.activeActivity ? <Text style={[styles.activeActivity, { color: c.blue600 }]}>Current activity · {displayActivity(deur.activeActivity)}</Text> : null}{work.custody ? <><Text style={{ color: c.textSecondary }}>Primary operator: {primaryOperatorDisplayName}</Text><Text style={{ color: c.textSecondary }}>Current operator: {currentOperatorDisplayName}</Text>{work.custody.turnoverStatus === 'PENDING' ? <Text style={{ color: c.textMuted }}>Turnover is pending acceptance. Activity controls remain locked.</Text> : null}</> : null}<Button label="VIEW DEUR DETAILS" variant="secondary" onPress={() => setShowDetails(true)} /></Card>
      <Card style={styles.card}><Text style={[styles.section, { color: c.textPrimary }]}>Meter review</Text><Text style={{ color: c.textSecondary }}>Type: {meterRequirementLabel(work.meterRequirement)}</Text>{work.meterRequirement === 'hourMeter' || work.meterRequirement === 'both' ? <><Text style={{ color: c.textSecondary }}>Opening hour meter: {deur.openingHourMeter === undefined ? 'Not recorded' : deur.openingHourMeter}</Text><Text style={{ color: c.textSecondary }}>Closing hour meter: {deur.closingHourMeter === undefined ? 'Not recorded' : deur.closingHourMeter}</Text></> : null}{work.meterRequirement === 'odometer' || work.meterRequirement === 'both' ? <><Text style={{ color: c.textSecondary }}>Opening odometer: {deur.openingOdometer === undefined ? 'Not recorded' : deur.openingOdometer}</Text><Text style={{ color: c.textSecondary }}>Closing odometer: {deur.closingOdometer === undefined ? 'Not recorded' : deur.closingOdometer}</Text></> : null}</Card>
      {deur.events?.length ? <Card style={styles.card}><Text style={[styles.section, { color: c.textPrimary }]}>Activity timeline</Text>{deur.events.map(event => <View key={event.id} style={styles.timelineRow}><View style={[styles.timelineDot, { backgroundColor: c.blue600 }]} /><View><Text style={{ color: c.textPrimary }}>{timelineActivityLabel(event.activity)} {event.action === 'start' ? 'started' : 'ended'}</Text><Text style={{ color: c.textMuted }}>{new Date(event.occurredAt).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })} · Event {event.sequence}</Text></View></View>)}</Card> : null}
      {canStartNew ? <><Text style={{ color: c.textMuted }}>This DEUR is complete. It will remain available in History while a new DEUR is created.</Text><Button label="START NEW DEUR" disabled={canonicalBusy} loading={canonicalBusy} onPress={() => void act('Start DEUR', () => startCanonicalDeur({ ...(openingHourMeter.trim() ? { openingHourMeter: Number(openingHourMeter) } : {}), ...(openingOdometer.trim() ? { openingOdometer: Number(openingOdometer) } : {}) }))} /></> : null}
      {isOpen && !isReadOnly && work.custody?.turnoverStatus === 'PENDING' ? <><Text style={{ color: c.textMuted }}>{canAcceptTurnover ? 'Accepting a turnover is online-only and transfers authority without changing the DEUR primary operator.' : 'Turnover is pending reliever acceptance. Activity controls remain locked.'}</Text>{canAcceptTurnover ? <Button label="ACCEPT TURNOVER" disabled={canonicalBusy} loading={canonicalBusy} onPress={() => void act('Accept turnover', acceptCanonicalTurnover)} /> : null}</> : canMutateOperationalState ? <><Text style={[styles.section, { color: c.textPrimary }]}>Operational state</Text>
      {work.turnoverTargets?.length ? <><Button label="TURN OVER DEUR" variant="secondary" disabled={canonicalBusy || offlineSyncState === 'OFFLINE' || offlineReadOnly} onPress={() => setShowTurnoverTargets(value => !value)} /><Text style={{ color: c.textMuted }}>{offlineSyncState === 'OFFLINE' ? 'Turnover requires an online connection.' : 'Nominate an eligible reliever. Your custody and current activity remain unchanged until acceptance.'}</Text>{showTurnoverTargets ? <View style={styles.controls}>{work.turnoverTargets.map(target => <Button key={target.operatorId} label={`TURN OVER TO ${target.displayName.toUpperCase()}`} disabled={canonicalBusy || offlineSyncState === 'OFFLINE' || offlineReadOnly} loading={canonicalBusy} onPress={() => void act('Turnover', async () => { const result=await initiateCanonicalTurnover(target.operatorId); if(result.success)setShowTurnoverTargets(false); return result; })} style={styles.control} />)}</View> : null}</> : null}
      <Text style={[styles.controlHint, { color: c.textMuted }]}>Select the current field activity</Text>
      <View style={styles.activityGrid}>{ACTIVITIES.map((label, index) => { const activity=mapMobileActivity(label); const active=deur.activeActivity === activity; return <ActivityButton key={label} label={label} active={active} wide={index === ACTIVITIES.length - 1} disabled={canonicalBusy || !canMutateActivity || offlineReadOnly || active} onPress={() => void act(label, () => transitionCanonicalActivity(activity, label === 'Idle' && idleReason ? { id: idleReason, label: idleReason } : undefined))} colors={c} />; })}</View>
      <Text style={[styles.controlHint, { color: c.textMuted }]}>Optional Idle Reason</Text>
      <View style={styles.controls}>{IDLE_REASONS.map((reason) => <Button key={reason} label={reason} variant={idleReason === reason ? 'primary' : 'ghost'} disabled={canonicalBusy || offlineReadOnly} onPress={() => setIdleReason(reason)} style={styles.reason} />)}</View>
      <Text style={[styles.controlHint, { color: c.textMuted }]}>Standby — equipment is ready but temporarily not operating.</Text>
      {meterRequired ? <><Text style={{ color: c.textMuted }}>Closing readings are required by the canonical rental expectation.</Text>{work.meterRequirement === 'hourMeter' || work.meterRequirement === 'both' ? <TextInput accessibilityLabel="Closing hour meter" value={closingHourMeter} onChangeText={setClosingHourMeter} placeholder="Closing hour meter" placeholderTextColor={c.textMuted} keyboardType="numeric" style={[styles.remarks, { color: c.textPrimary, borderColor: c.inputBorder, backgroundColor: c.inputBg }]} /> : null}{work.meterRequirement === 'odometer' || work.meterRequirement === 'both' ? <TextInput accessibilityLabel="Closing odometer" value={closingOdometer} onChangeText={setClosingOdometer} placeholder="Closing odometer" placeholderTextColor={c.textMuted} keyboardType="numeric" style={[styles.remarks, { color: c.textPrimary, borderColor: c.inputBorder, backgroundColor: c.inputBg }]} /> : null}</> : null}
      <View style={styles.terminalActions}><Text style={[styles.terminalHint, { color: c.textMuted }]}>Finish the shift first, then submit the completed DEUR for review.</Text><Button label="END SHIFT" variant="danger" disabled={canonicalBusy || !canMutateActivity || offlineReadOnly} onPress={() => void act('End Shift', endShift)} /><Button label="SUBMIT DEUR" disabled={canonicalBusy || uatSessionState !== 'ONLINE_AUTHENTICATED'} loading={canonicalBusy} onPress={() => void act('Submit', submitCanonicalDeur)} /></View></> : <Text style={{ color: c.textMuted }}>{isReadOnly ? 'This DEUR is read-only after submission. Customer review will follow.' : isOpen && !hasCustodyAuthority ? 'This DEUR is read-only after custody transfers. Customer review will follow.' : 'This DEUR is read-only after submission. Customer review will follow.'}</Text>}
    </>}
    {scenario8Replay.enabled ? <Card style={styles.card}><Text style={[styles.section, { color: c.textPrimary }]}>Test Tools</Text><Text style={{ color: c.textSecondary }}>End Shift original: {scenario8Replay.endShift.replace('_', ' ')}</Text><Button label="REPLAY EXACT END SHIFT" variant="secondary" disabled={canonicalBusy || scenario8Replay.endShift !== 'CAPTURED'} loading={canonicalBusy} onPress={() => void act('Exact End Shift replay', () => replayScenario8Terminal('END_SHIFT'))} /><Text style={{ color: c.textSecondary }}>Submit original: {scenario8Replay.submit.replace('_', ' ')}</Text><Button label="REPLAY EXACT SUBMIT" variant="secondary" disabled={canonicalBusy || scenario8Replay.submit !== 'CAPTURED'} loading={canonicalBusy} onPress={() => void act('Exact Submit replay', () => replayScenario8Terminal('SUBMIT'))} /><Text style={{ color: c.textMuted }}>Replay is available once after a successful submission.</Text></Card> : null}
    {message ? <Text style={{ color: c.textSecondary }}>{message}</Text> : null}
    <Text style={{ color: c.textMuted }}>After submission, the DEUR will be sent for customer review.</Text>
    {showDetails && deur ? <CanonicalDeurDetailsSheet work={work} deur={deur} colors={c} primaryOperatorDisplayName={primaryOperatorDisplayName ?? 'Unavailable'} currentOperatorDisplayName={currentOperatorDisplayName ?? 'Unavailable'} onClose={() => setShowDetails(false)} /> : null}
  </ScrollView>;
}

function displayActivity(activity: 'operation' | 'idle' | 'standby' | 'mealBreak' | 'breakdown') { return ({ operation: 'Operating', idle: 'Idle', standby: 'Standby', mealBreak: 'Meal Break', breakdown: 'Breakdown' } as const)[activity]; }
function timelineActivityLabel(activity: 'operation' | 'idle' | 'standby' | 'mealBreak' | 'breakdown' | 'shift') { return activity === 'shift' ? 'Shift' : displayActivity(activity); }
function meterRequirementLabel(requirement: 'none' | 'hourMeter' | 'odometer' | 'both' | undefined) { return requirement === 'hourMeter' ? 'Hour meter' : requirement === 'odometer' ? 'Odometer' : requirement === 'both' ? 'Hour meter + odometer' : 'Not required'; }
function statusVariant(status: string): 'blue' | 'emerald' | 'amber' | 'red' | 'slate' { if (status === 'In Progress' || status === 'Draft') return 'amber'; if (status === 'Submitted') return 'blue'; if (status === 'Acknowledged') return 'emerald'; if (status === 'Rejected') return 'red'; return 'slate'; }
function Metric({ label, value, color }: { label: string; value: string; color: string }) { return <View style={styles.metric}><Text style={styles.metricLabel}>{label}</Text><Text style={[styles.metricValue, { color }]}>{value}</Text></View>; }
function ActivityButton({ label, active, wide, disabled, onPress, colors: c }: { label: string; active: boolean; wide: boolean; disabled: boolean; onPress: () => void; colors: import('@/lib/theme').ThemeColors }) {
  return <Pressable accessibilityRole="button" accessibilityLabel={`Set activity ${label}`} accessibilityState={{ disabled, selected: active }} onPress={onPress} disabled={disabled} style={[styles.activityButton, wide && styles.activityButtonWide, { backgroundColor: active ? c.blue600 : c.surface, borderColor: active ? c.blue600 : c.surfaceBorder }, disabled && !active && styles.disabled]}><Text style={[styles.activityButtonLabel, { color: active ? c.white : c.textPrimary }]}>{label.toUpperCase()}</Text>{active ? <Text style={[styles.activityButtonState, { color: c.white }]}>ACTIVE</Text> : null}</Pressable>;
}
const styles = StyleSheet.create({ center: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: spacing.xl }, content: { padding: spacing.lg, gap: spacing.md, maxWidth: 640, width: '100%', alignSelf: 'center' }, title: { fontFamily: 'Manrope-ExtraBold', fontSize: 24 }, section: { fontFamily: 'Manrope-Bold', fontSize: 16 }, name: { fontFamily: 'Manrope-Bold', fontSize: 18 }, overline: { fontFamily: 'Manrope-ExtraBold', fontSize: 11, letterSpacing: 0.8 }, card: { gap: spacing.sm }, deurHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm }, activeActivity: { fontFamily: 'Manrope-Bold' }, kpiGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.xs }, metric: { flexGrow: 1, flexBasis: '22%', minWidth: 78, padding: spacing.sm, borderRadius: 8, backgroundColor: 'rgba(148,163,184,0.10)' }, metricLabel: { fontFamily: 'Manrope-Medium', fontSize: 11, color: '#64748b' }, metricValue: { fontFamily: 'Manrope-Bold', fontSize: 14, marginTop: 2 }, controls: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, activityGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm }, activityButton: { flexGrow: 1, flexBasis: '46%', minWidth: '46%', minHeight: 76, padding: spacing.md, borderWidth: 1, borderRadius: 14, alignItems: 'center', justifyContent: 'center', gap: spacing.xs }, activityButtonWide: { flexBasis: '100%' }, activityButtonLabel: { fontFamily: 'Manrope-ExtraBold', fontSize: 15, textAlign: 'center' }, activityButtonState: { fontFamily: 'Manrope-Bold', fontSize: 10, letterSpacing: 0.8 }, disabled: { opacity: 0.5 }, control: { minWidth: '46%', flexGrow: 1 }, reason: { minHeight: 38, paddingVertical: spacing.sm }, controlHint: { fontFamily: 'Manrope-Medium', fontSize: 12 }, terminalActions: { gap: spacing.sm, paddingTop: spacing.sm }, terminalHint: { fontFamily: 'Manrope-Medium', fontSize: 12 }, remarks: { minHeight: 72, borderWidth: 1, borderRadius: 10, padding: 12, textAlignVertical: 'top' }, timelineRow: { flexDirection: 'row', alignItems: 'flex-start', gap: spacing.sm, paddingVertical: spacing.xs }, timelineDot: { width: 9, height: 9, borderRadius: 5, marginTop: 4 }, warning: { padding: spacing.md, borderRadius: 10, overflow: 'hidden' } });
