import { useState } from 'react';
import { StyleSheet, Text, View, ScrollView, Switch, TouchableOpacity } from 'react-native';
import { LogOut, Truck, FileText, Info, Sun, Moon } from 'lucide-react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { useRouter } from 'expo-router';
import { useTheme } from '@/lib/useTheme';
import { useAuth } from '@/lib/auth';
import type { CanonicalOperatorWork } from '@/lib/canonical/contracts.generated';
import { Card } from './Card';
import { StatusChip } from './StatusChip';
import { Button } from './Button';
import { spacing, fonts } from '@/lib/theme';

export function CanonicalProfile({ work }: { work: CanonicalOperatorWork }) {
  const { logout, operator: sessionOperator, refreshCanonicalWork } = useAuth(); const { mode, toggle, colors: c } = useTheme(); const insets = useSafeAreaInsets(); const router = useRouter();
  const [refreshing,setRefreshing]=useState(false); const [refreshMessage,setRefreshMessage]=useState<string|null>(null);
  const [loggingOut,setLoggingOut]=useState(false); const [logoutMessage,setLogoutMessage]=useState<string|null>(null);
  const refresh=async()=>{if(refreshing)return;setRefreshing(true);setRefreshMessage(null);try{if(!await refreshCanonicalWork())setRefreshMessage('Unable to refresh. Current offline data remains available.');}catch{setRefreshMessage('Unable to refresh. Current offline data remains available.');}finally{setRefreshing(false);}};
  const handleLogout=async()=>{if(loggingOut)return;setLoggingOut(true);setLogoutMessage(null);if(await logout())router.replace('/login');else{setLogoutMessage('Logout could not be saved. Try again.');setLoggingOut(false);}};
  const operator = work.identity; const initials = operator.operatorName.split(/\s+/).map(part => part[0]).slice(0, 2).join('').toUpperCase();
  const loginName = sessionOperator?.loginName && !isOpaqueIdentifier(sessionOperator.loginName) ? sessionOperator.loginName : null;
  return <ScrollView style={[styles.container, { backgroundColor: c.background }]} contentContainerStyle={[styles.content, { paddingTop: spacing.lg + insets.top, paddingBottom: spacing.xxxl + 60 + insets.bottom }]}>
    <View style={styles.header}><View style={[styles.avatar, { backgroundColor: c.blue600 }]}><Text style={styles.avatarText}>{initials}</Text></View><Text style={[styles.name, { color: c.textPrimary }]}>{operator.operatorName}</Text><Text style={[styles.muted, { color: c.textMuted }]}>Operator</Text></View>
    <Button label={refreshing ? 'REFRESHING…' : 'REFRESH CURRENT ASSIGNMENT'} variant="secondary" disabled={refreshing} loading={refreshing} onPress={() => void refresh()} />
    {refreshMessage?<Text style={[styles.muted,{color:c.amber500}]}>{refreshMessage}</Text>:null}
    <Text style={[styles.section, { color: c.textMuted }]}>APPEARANCE</Text><Card><View style={styles.row}>{mode === 'dark' ? <Moon size={16} color={c.textSecondary} /> : <Sun size={16} color={c.textSecondary} />}<Text style={[styles.label, { color: c.textSecondary }]}>Dark Mode</Text><Switch value={mode === 'dark'} onValueChange={toggle} trackColor={{ false: c.slate200, true: c.blue600 }} thumbColor="#ffffff" /></View></Card>
    <Text style={[styles.section, { color: c.textMuted }]}>ACCOUNT</Text><Card style={styles.compactCard}>{loginName ? <><View style={styles.row}><Text style={[styles.label, { color: c.textSecondary }]}>Login name</Text><Text style={[styles.value, styles.valueFlexible, { color: c.textPrimary }]} numberOfLines={1}>{loginName}</Text></View><View style={[styles.divider, { backgroundColor: c.slate100 }]} /></> : null}<View style={styles.row}><Text style={[styles.label, { color: c.textSecondary }]}>Role</Text><Text style={[styles.value, { color: c.textPrimary }]}>Operator</Text></View></Card>
    <Text style={[styles.section, { color: c.textMuted }]}>CURRENT ASSIGNMENT</Text><Card style={styles.compactCard}><View style={styles.assignment}><Truck size={18} color={c.blue600} /><View><Text style={[styles.muted, { color: c.textMuted }]}>Equipment</Text><Text style={[styles.value, { color: c.textPrimary }]}>{work.equipment.name}</Text><Text style={[styles.muted, { color: c.textMuted }]}>{work.equipment.assetNumber}</Text></View></View><View style={[styles.divider, { backgroundColor: c.slate100 }]} /><View style={styles.assignment}><FileText size={18} color={c.blue600} /><View><Text style={[styles.muted, { color: c.textMuted }]}>Project / Rental</Text><Text style={[styles.value, { color: c.textPrimary }]}>{work.assignment.projectName || 'Project unavailable'}</Text><Text style={[styles.muted, { color: c.textMuted }]}>{work.rental.rentalNumber}</Text><StatusChip label={work.rental.status.toUpperCase()} variant="blue" /></View></View><View style={[styles.divider, { backgroundColor: c.slate100 }]} /><View style={styles.assignment}><Text style={{ color: c.blue600 }}>●</Text><View><Text style={[styles.muted, { color: c.textMuted }]}>Assignment</Text><Text style={[styles.value, { color: c.textPrimary }]}>{work.assignment.status}</Text>{!work.deurEligible?<Text style={[styles.muted,{color:c.amber500}]}>DEUR becomes available when the rental is activated.</Text>:null}</View></View></Card>
    <Text style={[styles.section, { color: c.textMuted }]}>APPLICATION</Text><Card style={styles.compactCard}><View style={styles.row}><Info size={16} color={c.textMuted} /><Text style={[styles.label, { color: c.textSecondary }]}>Session</Text><Text style={[styles.value, { color: c.textPrimary }]}>Active</Text></View></Card>
    {logoutMessage?<Text accessibilityRole="alert" style={[styles.muted,{color:c.red500}]}>{logoutMessage}</Text>:null}
    <TouchableOpacity style={[styles.logout, { backgroundColor: c.dangerBg }]} disabled={loggingOut} onPress={() => void handleLogout()}><LogOut size={20} color={c.red500} /><Text style={[styles.logoutText, { color: c.red500 }]}>{loggingOut?'Logging out…':'Logout'}</Text></TouchableOpacity>
  </ScrollView>;
}
const isOpaqueIdentifier = (value: string) => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(value);
const styles = StyleSheet.create({ container: { flex: 1 }, content: { padding: spacing.lg, gap: spacing.md }, header: { alignItems: 'center', gap: 6, paddingVertical: 10 }, avatar: { width: 64, height: 64, borderRadius: 32, alignItems: 'center', justifyContent: 'center' }, avatarText: { fontFamily: fonts.extrabold, fontSize: 24, color: '#fff' }, name: { fontFamily: fonts.extrabold, fontSize: 22 }, muted: { fontFamily: fonts.medium, fontSize: 13 }, section: { fontFamily: fonts.extrabold, fontSize: 13, marginTop: 8 }, compactCard: { padding: 0, overflow: 'hidden' }, row: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 16, paddingVertical: 10 }, label: { flex: 1, fontFamily: fonts.regular, fontSize: 14 }, value: { fontFamily: fonts.bold, fontSize: 14 }, valueFlexible: { maxWidth: '62%' }, divider: { height: 1, marginLeft: 16 }, assignment: { flexDirection: 'row', gap: 12, paddingHorizontal: 16, paddingVertical: 10, alignItems: 'flex-start' }, logout: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 8, borderRadius: 12, paddingVertical: 14, minHeight: 52, marginTop: 8 }, logoutText: { fontFamily: fonts.bold, fontSize: 16 } });
